### ISSUE TITLE
Module installed in app/code and vendor

### ISSUE THREAD

**Issue by imsergiobernal** [manishjoy/magento2-delete-orders#6]
Hello I see that I have the extension installed in app/code and vendor, is this normal? Maybe I commited an error? Can I delete one?

**Comment by manishjoy** [comment]
This extension should be installed in app/code. As per Magento standards, custom extension are put in app/code and core modules in vendor.

**Comment by OZZlE** [comment]
Wrong all apps should only use the vendor folder when using composer. Not sure it can use anything else when installed with composer actually.. except for cache things..

**Comment by OZZlE** [comment]
Well apparently you can.. this is very bad practice and wrong!

**Comment by manishjoy** [comment]
**Reply to https://github.com/manishjoy/magento2-delete-orders/issues/6#issuecomment-321591457**

I agree, that extensions can be installed using composer and it would be placed in vendor. But in general, third party extensions are placed in **app/code** directory.

**Comment by manishjoy** [comment]
**Reply to https://github.com/manishjoy/magento2-delete-orders/issues/6#issuecomment-321595445**

This isn't a bad practice at all. I know, I am using direct SQL Queries but it does the same thing that could be done via CRUD operations.

**Comment by OZZlE** [comment]
Why not put the files in the pub/media folder then? :D Who ever said it was bad practice :D 

I "like" that I had to commit these files to my project instead of just modifying composer.json & composer.lock, eg:

`composer require thecodingtutor/magento2-delete-orders:*`

Maybe you want to read up on: https://getcomposer.org/doc/

**Comment by OZZlE** [comment]
By the way your module works well otherwise :) Thank you
